package types

const (
	APP_SERVICE                           = "APP_SERVICE"
	APP_SERVICE_PLAN                      = "APP_SERVICE_PLAN"
	APPLICATION_GATEWAY                   = "APPLICATION_GATEWAY"
	APPLICATION_INSIGHTS                  = "APPLICATION_INSIGHTS"
	APPLICATION_SECURITY_GROUP            = "APPLICATION_SECURITY_GROUP"
	CONTAINER_REGISTRY                    = "CONTAINER_REGISTRY"
	COSMOS                                = "COSMOS"
	DATA_FACTORY                          = "DATA_FACTORY"
	DATA_FACTORY_INTEGRATION_RUNTIME      = "DATA_FACTORY_INTEGRATION_RUNTIME"
	DATA_FACTORY_MANAGED_PRIVATE_ENDPOINT = "DATA_FACTORY_MANAGED_PRIVATE_ENDPOINT"
	DATABRICKS_WORKSPACE                  = "DATABRICKS_WORKSPACE"
	DNS_RECORD                            = "DNS_RECORD"
	FUNCTION_APP                          = "FUNCTION_APP"
	KEY_VAULT                             = "KEY_VAULT"
	LOAD_BALANCER                         = "LOAD_BALANCER"
	LOAD_BALANCER_FRONTEND                = "LOAD_BALANCER_FRONTEND"
	LOG_ANALYTICS                         = "LOG_ANALYTICS"
	LOGIC_APP                             = "LOGIC_APP"
	NAT_GATEWAY                           = "NAT_GATEWAY"
	NETWORK_INTERFACE                     = "NETWORK_INTERFACE"
	NETWORK_SECURITY_GROUP                = "NETWORK_SECURITY_GROUP"
	POSTGRES_SQL_SERVER                   = "POSTGRES_SQL_SERVER"
	PRIVATE_DNS_ZONE                      = "PRIVATE_DNS_ZONE"
	PRIVATE_ENDPOINT                      = "PRIVATE_ENDPOINT"
	PRIVATE_LINK_SERVICE                  = "PRIVATE_LINK_SERVICE"
	PUBLIC_IP_ADDRESS                     = "PUBLIC_IP_ADDRESS"
	RECOVERY_SERVICE_VAULT                = "RECOVERY_SERVICE_VAULT"
	REDIS                                 = "REDIS"
	ROUTE_TABLE                           = "ROUTE_TABLE"
	SQL_DATABASE                          = "SQL_DATABASE"
	SQL_SERVER                            = "SQL_SERVER"
	STORAGE_ACCOUNT                       = "STORAGE_ACCOUNT"
	SUBNET                                = "SUBNET"
	SUBSCRIPTION                          = "SUBSCRIPTION"
	VIRTUAL_MACHINE                       = "VIRTUAL_MACHINE"
	VIRTUAL_MACHINE_SCALE_SET             = "VIRTUAL_MACHINE_SCALE_SET"
	VIRTUAL_NETWORK                       = "VIRTUAL_NETWORK"
)
