package images

const (
	APP_SERVICE                           = "img/lib/azure2/app_services/App_Services.svg"
	APP_SERVICE_PLAN                      = "img/lib/azure2/app_services/App_Service_Plans.svg"
	APPLICATION_GATEWAY                   = "img/lib/azure2/networking/Application_Gateways.svg"
	APPLICATION_INSIGHTS                  = "img/lib/azure2/devops/Application_Insights.svg"
	APPLICATION_SECURITY_GROUP            = "img/lib/azure2/security/Application_Security_Groups.svg"
	BASTION                               = "img/lib/azure2/networking/Bastions.svg"
	CONTAINER_REGISTRY                    = "img/lib/azure2/containers/Container_Registries.svg"
	COSMOS                                = "img/lib/azure2/databases/Azure_Cosmos_DB.svg"
	DATA_FACTORY                          = "img/lib/azure2/databases/Data_Factory.svg"
	DATA_FACTORY_INTEGRATION_RUNTIME      = VIRTUAL_MACHINE
	DATA_FACTORY_MANAGED_PRIVATE_ENDPOINT = PRIVATE_ENDPOINT
	DATABRICKS_WORKSPACE                  = "img/lib/azure2/analytics/Azure_Databricks.svg"
	FUNCTION_APP                          = "img/lib/azure2/compute/Function_Apps.svg"
	KEY_VAULT                             = "img/lib/azure2/security/Key_Vaults.svg"
	LOAD_BALANCER                         = "img/lib/azure2/networking/Load_Balancers.svg"
	LOAD_BALANCER_FRONTEND                = PUBLIC_IP_ADDRESS
	LOG_ANALYTICS                         = "img/lib/azure2/management_governance/Log_Analytics_Workspaces.svg"
	LOGIC_APP                             = "img/lib/azure2/integration/Logic_Apps.svg"
	NAT_GATEWAY                           = "img/lib/azure2/networking/NAT.svg"
	NETWORK_INTERFACE                     = "img/lib/azure2/networking/Network_Interfaces.svg"
	NETWORK_SECURITY_GROUP                = "img/lib/azure2/networking/Network_Security_Groups.svg"
	POSTGRES_SQL_SERVER                   = "img/lib/azure2/databases/Azure_Database_PostgreSQL_Server.svg"
	PRIVATE_DNS_ZONE                      = "img/lib/azure2/networking/DNS_Zones.svg"
	PRIVATE_ENDPOINT                      = "img/lib/azure2/other/Private_Endpoints.svg"
	PRIVATE_LINK_SERVICE                  = "img/lib/azure2/networking/Private_Link_Service.svg"
	PUBLIC_IP_ADDRESS                     = "img/lib/azure2/networking/Public_IP_Addresses.svg"
	RECOVERY_SERVICE_VAULT                = "img/lib/azure2/storage/Recovery_Services_Vaults.svg"
	REDIS                                 = "img/lib/azure2/databases/Cache_Redis.svg"
	SUBSCRIPTION                          = "img/lib/azure2/general/Subscriptions.svg"
	SQL_DATABASE                          = "img/lib/azure2/databases/SQL_Database.svg"
	SQL_SERVER                            = "img/lib/azure2/databases/SQL_Server.svg"
	STATIC_WEB_APP                        = "img/lib/azure2/preview/Static_Apps.svg"
	STORAGE_ACCOUNT                       = "img/lib/azure2/storage/Storage_Accounts.svg"
	SUBNET                                = "img/lib/azure2/networking/Subnet.svg"
	VIRTUAL_MACHINE                       = "img/lib/azure2/compute/Virtual_Machine.svg"
	VIRTUAL_MACHINE_SCALE_SET             = "img/lib/azure2/compute/VM_Scale_Sets.svg"
	VIRTUAL_NETWORK                       = "img/lib/azure2/networking/Virtual_Networks.svg"
)
